### ISSUE TITLE
Repository configuration

### ISSUE THREAD

**Issue by alexey62soft** [MalanichevaAnna/MalanichevaAnna_dotNet#2]
Add .gitignore to the root of the repository and remove VS2019 configs and Builds (look `.gitignore`).
PS Make it without Pull Request.

**Comment by MalanichevaAnna** [comment]
added

**Comment by alexey62soft** [comment]
Yes, you added gitignore, but build trash and VisualStudio configs still in the repo.
Please, remove all of them from the master branch (and add gitignore to that) without PR.
Only after that, pull these changes to LR-2 branch and removed build trash and VisualStudio configs from the second lab.

**Comment by alexey62soft** [comment]
~90 files in PR should confuse you)

**Comment by MalanichevaAnna** [comment]
fixed))
